//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryShiryaev2isp11_17.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookInUse
    {
        public int ID { get; set; }
        public int BookID { get; set; }
        public int CustID { get; set; }
        public System.DateTime DateOfIssue { get; set; }
        public Nullable<int> EmployeID { get; set; }
        public System.DateTime DateReturn { get; set; }
        public Nullable<bool> IsPaidFor { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Employe Employe { get; set; }
    }
}
